service: serverless-authorizer-with-cognito-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-offline

functions:
  authorizerFunc:
    handler: src/authorizer/handler.handler
    name: ${self:service}-${self:provider.stage}-authorizer

  public:
    handler: src/handler.public
    name: ${self:service}-${self:provider.stage}-public
    events:
      - http:
          path: public
          method: any
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - Authorization

  private:
    handler: src/handler.private
    name: ${self:service}-${self:provider.stage}-private
    events:
      - http:
          path: private
          method: any
          authorizer: authorizerFunc
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - Authorization
